### PR TITLE
docs update

### PR DESCRIPTION
**Pull request by alex10342**
i update the docs sir!!!111!!1

### CODE REVIEW

**Comment by Crazycatwastaken** [comment]
Sorry, but I don't like jinxs.

**Comment by alex10342** [comment]
noooooo my pull request :(((((((

**Comment by alex10342** [comment]
YAY IT OPENED :D

**Comment by Crazycatwastaken** [comment]
You know, I like jinx.

**Comment by alex10342** [comment]
:0

**Pull request closed without merging**
